# Generated by Django 2.2.3 on 2020-02-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
